#!/bin/sh
# This script will put the buttons vertically centered on the titlebar.
# The "stuck" button
STUCK_normal="stuckfcs_gray_original.png"
STUCK_unfocus="stuckufcs_gray_original.xpm"
composite -gravity center $STUCK_normal ./pixmaps/titlefcs.xpm ./pixmaps/stuckfcs.xpm
composite -gravity center $STUCK_normal ./pixmaps/titlefcs.xpm ./pixmaps/stickpr.xpm
composite -gravity center $STUCK_unfocus ./pixmaps/titlefcs.xpm ./pixmaps/stuckufcs.xpm
composite -gravity center closefcs_custom.xpm ./pixmaps/titlefcs.xpm ./pixmaps/closefcs.xpm
composite -gravity center maxfcs_original.xpm ./pixmaps/titlefcs.xpm ./pixmaps/maxfcs.xpm
composite -gravity center minfcs_original.xpm ./pixmaps/titlefcs.xpm ./pixmaps/minfcs.xpm
composite -gravity center closeufcs_custom.xpm ./pixmaps/titlefcs.xpm ./pixmaps/closeufcs.xpm
composite -gravity center maxufcs_original.xpm ./pixmaps/titlefcs.xpm ./pixmaps/maxufcs.xpm
composite -gravity center minufcs_original.xpm ./pixmaps/titlefcs.xpm ./pixmaps/minufcs.xpm
composite -gravity center closepr_custom.xpm ./pixmaps/titlefcs.xpm ./pixmaps/closepr.xpm
composite -gravity center maxpr_original.xpm ./pixmaps/titlefcs.xpm ./pixmaps/maxpr.xpm
composite -gravity center minpr_original.xpm ./pixmaps/titlefcs.xpm ./pixmaps/minpr.xpm
cp -f ./pixmaps/titlefcs.xpm ./pixmaps/menu_title.xpm
cp -f ./pixmaps/titlefcs.xpm ./pixmaps/shadefcs.xpm
cp -f ./pixmaps/titlefcs.xpm ./pixmaps/shadepr.xpm
cp -f ./pixmaps/titlefcs.xpm ./pixmaps/shadeufcs.xpm
cp -f ./pixmaps/titlefcs.xpm ./pixmaps/stickfcs.xpm
cp -f ./pixmaps/titlefcs.xpm ./pixmaps/stickufcs.xpm
cp -f ./pixmaps/titlefcs.xpm ./pixmaps/stuckpr.xpm
cp -f ./pixmaps/titlefcs.xpm ./pixmaps/tbarfcs.xpm
cp -f ./pixmaps/titlefcs.xpm ./pixmaps/tbarufcs.xpm
cp -f ./pixmaps/titlefcs.xpm ./pixmaps/titleufcs.xpm
cp -f ./pixmaps/titlefcs.xpm ./pixmaps/unshadefcs.xpm
cp -f ./pixmaps/titlefcs.xpm ./pixmaps/unshadepr.xpm
cp -f ./pixmaps/titlefcs.xpm ./pixmaps/unshadeufcs.xpm
echo Done. Everything ok.
exit

