#!/bin/sh
# This script is to be used with a customized "closefcs_original.xpm".
# Uncommenting the lines adds a cross on the button.
GRADIENT="white"
CROSS_normal="close_light.png"
CROSS_pressed="close_dark.png"
convert closefcs_original.xpm tmp.png
mogrify -region '22x1+0+13' -fill $GRADIENT -colorize 3% tmp.png
mogrify -region '22x1+0+12' -fill $GRADIENT -colorize 6% tmp.png
mogrify -region '22x1+0+11' -fill $GRADIENT -colorize 9% tmp.png
mogrify -region '22x1+0+10' -fill $GRADIENT -colorize 12% tmp.png
mogrify -region '22x1+0+9' -fill $GRADIENT -colorize 15% tmp.png
mogrify -region '22x1+0+8' -fill $GRADIENT -colorize 18% tmp.png
mogrify -region '22x1+0+7' -fill $GRADIENT -colorize 21% tmp.png
mogrify -region '22x1+0+6' -fill $GRADIENT -colorize 24% tmp.png
mogrify -region '22x1+0+5' -fill $GRADIENT -colorize 27% tmp.png
mogrify -region '22x1+0+4' -fill $GRADIENT -colorize 30% tmp.png
mogrify -region '22x1+0+3' -fill $GRADIENT -colorize 33% tmp.png
mogrify -region '22x1+0+2' -fill $GRADIENT -colorize 36% tmp.png
mogrify -region '22x1+0+1' -fill $GRADIENT -colorize 39% tmp.png
mogrify -region '21x1+0+0' -fill $GRADIENT -colorize 42% tmp.png
# The next line draws the separation between the maximize and close buttons
# You can make this line darker with for example -fill black -colorize 20%
mogrify -region '1x16+0+0' -fill gray -colorize 20% tmp.png
mogrify -region '21x1+0+15' -fill gray -colorize 20% tmp.png
mogrify -region '21x1+0+0' -fill gray -colorize 20% tmp.png
mogrify -region '1x14+21+1' -fill gray -colorize 20% tmp.png
convert tmp.png closefcs_custom.xpm
# composite -gravity center $CROSS_normal tmp.png closefcs_custom.xpm
convert tmp.png -fill white -colorize 10% closepr_custom.xpm
# composite -gravity center $CROSS_pressed tmp.png closepr_custom.xpm
convert closefcs_custom.xpm -fill gray -colorize 30% closeufcs_custom.xpm
rm tmp.png
echo Done. Everything ok.
exit

