#!/bin/sh
# This script will put the buttons on the bottom of the titlebar.
# The "stuck" button
STUCK_normal="stuckfcs_gray_original.png"
STUCK_unfocus="stuckufcs_gray_original.xpm"
composite -geometry +0+4 -gravity south $STUCK_normal ./pixmaps/titleufcs.xpm ./pixmaps/stuckfcs.xpm
composite -geometry +0+4 -gravity south $STUCK_normal ./pixmaps/titleufcs.xpm ./pixmaps/stickpr.xpm
composite -geometry +0+4 -gravity south $STUCK_unfocus ./pixmaps/titleufcs.xpm ./pixmaps/stuckufcs.xpm
composite -gravity south closefcs_custom.xpm ./pixmaps/titleufcs.xpm ./pixmaps/closefcs.xpm
composite -gravity south maxfcs_original.xpm ./pixmaps/titleufcs.xpm ./pixmaps/maxfcs.xpm
composite -gravity south minfcs_original.xpm ./pixmaps/titleufcs.xpm ./pixmaps/minfcs.xpm
composite -gravity south closeufcs_custom.xpm ./pixmaps/titleufcs.xpm ./pixmaps/closeufcs.xpm
composite -gravity south maxufcs_original.xpm ./pixmaps/titleufcs.xpm ./pixmaps/maxufcs.xpm
composite -gravity south minufcs_original.xpm ./pixmaps/titleufcs.xpm ./pixmaps/minufcs.xpm
composite -gravity south closepr_custom.xpm ./pixmaps/titleufcs.xpm ./pixmaps/closepr.xpm
composite -gravity south maxpr_original.xpm ./pixmaps/titleufcs.xpm ./pixmaps/maxpr.xpm
composite -gravity south minpr_original.xpm ./pixmaps/titleufcs.xpm ./pixmaps/minpr.xpm
cp -f ./pixmaps/titleufcs.xpm ./pixmaps/shadefcs.xpm
cp -f ./pixmaps/titleufcs.xpm ./pixmaps/shadepr.xpm
cp -f ./pixmaps/titleufcs.xpm ./pixmaps/shadeufcs.xpm
cp -f ./pixmaps/titleufcs.xpm ./pixmaps/stickfcs.xpm
cp -f ./pixmaps/titleufcs.xpm ./pixmaps/stickufcs.xpm
cp -f ./pixmaps/titleufcs.xpm ./pixmaps/stuckpr.xpm
cp -f ./pixmaps/titleufcs.xpm ./pixmaps/unshadefcs.xpm
cp -f ./pixmaps/titleufcs.xpm ./pixmaps/unshadepr.xpm
cp -f ./pixmaps/titleufcs.xpm ./pixmaps/unshadeufcs.xpm
cp -f ./pixmaps/titleufcs.xpm ./pixmaps/menu_title.xpm
cp -f ./pixmaps/titleufcs.xpm ./pixmaps/tbarfcs.xpm
cp -f ./pixmaps/titleufcs.xpm ./pixmaps/tbarufcs.xpm
echo Done. Everything ok.
exit

