#!/usr/bin/env ruby



def lap
  	%x[xrandr --output LVDS1 --auto]
	%x[xrandr --output VGA1 --off]
end

def vga
  	%x[xrandr --output VGA1 --auto]
	%x[xrandr --output LVDS1 --off]
end

def clone
  	%x[xrandr --output LVDS1 --auto --primary]
	%x[xrandr --output VGA1 --auto --same-as LVDS1]
end

def ext
  	%x[xrandr --output LVDS1 --auto --primary]
	%x[xrandr --output VGA1 --auto --above LVDS1]
end

def def_action
  	ext
end

case ARGV[0]
when /lap/i 		then lap
when /vga/i 		then vga
when /clone/i 		then clone
when /ext/i 		then ext
when /help/i 		then puts "lap | vga | clone | ext"
else			def_action
end

