#!/bin/bash

usage="
YABS - Yet Another Battery Status\n
(C) 2009 XayOn (David Francos Cuatero) \n
		<yo.orco@gmail.com>\n
USAGE:\n
\t $0 [OPTIONS]\n\n
OPTIONS:\n
\t	-p | --percent      Show percentage instead of \n
\t	-v | --verbose      Verbose output, localized.\n
\t	-d | --dir     dire ACPI Battery dir (/proc/acpi/battery)\n
\t	-a | --ac_word word Word to show when ac (*AC*)\n
\t	-i | --iterate      Show all batteries status\n
\t	-b | --battery batt Show infor for BAT\n
\t	-h | --help         Shows this menu\n
"

percent=0;verbose=0;dir="/proc/acpi/battery/";state="state";info="info";battery="BAT1";iterate=0;acw="*AC*"

while getopts "hpvd:a:ib:" option; do
		case $option in
			p|percent) percent=1;;
			v|verbose) verbose=1;;
			d|dir) dir=$OPTARG;;
			a|ac_word) acw=$OPTARG;;
			i|iterate) iterate=1 ;;
			b|battery) battery=$OPTARG;;
			h|"help" ) echo -e $usage;exit;;
		esac
done

_read_battery(){ bat=${1}
	if [ $verbose == 1 ]; then echo -n `gettext "Battery left "` " "; fi
	if [ $percent == 1 ]; then echo $(( $(($(cat $dir/$bat/$state |grep remaining |awk {'print $3'})*100)) / $(cat $dir/$bat/$info |grep last|awk {'print $4'}))) "%" ;
	else echo -n `cat $dir/$bat/$state|grep remaining| awk {'print $3'}` " of "; echo $(cat $dir/$bat/$info|grep last|awk {'print $4'}) "mAh";fi
}

if on_ac_power ; then echo $acw;
else 
	if [ $iterate == 1 ]; then for batn in `ls $dir` ; do _read_battery $batn;done
	else if [ "$battery" != "" ]; then _read_battery $battery;else _read_battery BAT1;fi;fi;fi
