# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

source ~/.zsh/antigen.zsh

# antigen bundle bundler
antigen bundle command-not-found
# antigen bundle colored-man
# antigen bundle extract
# antigen bundle jump
# antigen bundle gem
# antigen bundle gitfast
# antigen bundle mvn
# antigen bundle rvm
# antigen bundle sudo
# antigen bundle systemd
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle Tarrasch/zsh-functional
antigen bundle mix

source ~/.zsh/exports.zsh
source ~/.zsh/keybindings.zsh
source ~/.zsh/aliases.zsh
source ~/.zsh/functions.zsh
source ~/.zsh/promptleft.zsh
source ~/.zsh/promptright.zsh
source ~/.zsh/history.zsh
source ~/.zsh/completion.zsh
source ~/.zsh/directories.zsh

# This one is not committed to dotfiles repository.
# There I keep secret env variables.
if [[ -a ~/.zsh/secrets.zsh ]]; then
	source ~/.zsh/secrets.zsh
fi

# source ~/.zsh/completions/tmuxinator.zsh
# source ~/.zsh/completions/zeus.zsh

# zmodload zsh/mathfunc
autoload zmv

autoload -U add-zsh-hook
function switch_term_colors() {
	if [[ ($(date +%H) -gt 20) || ($(date +%H) -lt 6) ]]
	then
		switch-theme-night
	else
		switch-theme-day
	fi
}
if (( $+commands[konsoleprofile] ))
then
	add-zsh-hook precmd switch_term_colors
fi

# Auto cd in directories
setopt autocd

# Extended Globbing, for example: `cp ^*.(tar|bz2|gz)`
setopt extendedglob

ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern cursor root)
ZSH_HIGHLIGHT_STYLES[path]='fg=green,bold'
ZSH_HIGHLIGHT_STYLES[globbing]='fg=magenta,bold'

if type "keychain" > /dev/null; then
	eval $(keychain --eval --agents ssh --noask -Q --quiet ~/.ssh/id_rsa)
	eval $(keychain --eval --agents ssh --noask -Q --quiet /media/projs/repositories/arkency/kitchen/chef.key)
	eval $(keychain --eval --agents ssh --noask -Q --quiet /media/projs/repositories/pons/kitchen/chef.key)
fi

# RVM
[[ (-s $HOME/.rvm) ]] && source $HOME/.rvm/scripts/rvm

# Opam
. /home/swistak35/.opam/opam-init/init.zsh > /dev/null 2> /dev/null || true

# rbenv
eval "$(rbenv init -)"

# nix
if [[ -a /home/swistak35/.nix-profile/etc/profile.d/nix.sh ]]
then
	# export LOCALE_ARCHIVE=/home/swistak35/locale-archive
	export LOCALE_ARCHIVE=/nix/store/4yhkx5xr14q3phjdqds3rhckrw4107xx-glibc-locales-2.21/lib/locale/locale-archive
	. /home/swistak35/.nix-profile/etc/profile.d/nix.sh
fi

